=head1 NAME

libptytty - OS independent and secure pty/tty and utmp/wtmp/lastlog handling

=head1 SYNOPSIS

   -lptytty

=head1 DESCRIPTION

=head1 INTEGRATION

make setuid/setgid etc.

=head1 THE ptytty CLASS

=over 4

=item new ptytty

...

=back

=head1 BUGS

You kiddin'?

=head1 AUTHORS

Emanuele Giaquinta L<< <e.giaquinta@glauco.it> >>, Marc Alexander Lehmann
L<< <rxvt-unicode@schmorp.de> >>.
